name: Run Single Pynguin

on:
  workflow_call:
    inputs:
      project-link:
        required: true
        type: string
      release-name:
        required: true
        type: string
    secrets: 
      GH_ACCESS_TOKEN:
        required: true 
jobs:
  run-comparison:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            python-version: '3.10'

        - name: Setup variables
          run: |
              REPO_URL=$(echo "${{ inputs.project-link }}" | sed 's/;.*//')
              REPO_NAME="${REPO_URL##*/}"  # This strips everything before the last '/' character
              OWNER_NAME="${REPO_URL%/$REPO_NAME}"  # Removes the repo name from the URL, leaving the owner path
              OWNER_NAME="${OWNER_NAME##*/}"  # Extracts only the owner name
              FULL_REPO_NAME="$OWNER_NAME-$REPO_NAME"  # Combines owner and repository names with a dash

              ZIP_FILE="${FULL_REPO_NAME}_Experiment_PYMOP.zip"
              echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
              echo "FULL_REPO_NAME=$FULL_REPO_NAME" >> $GITHUB_ENV
              echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
              echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          shell: bash
        
        - name: Prepare results dir
          run: |
            cd ./test-generation-with-pynguin
            mkdir ./results
            
        - name: Run Pynguin
          run: |
            cd ./test-generation-with-pynguin
            ls -l
            chmod +x ./run_pynguin.sh
            ./run_pynguin.sh "${{ inputs.project-link }}"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

        - name: Run Original Tests
          id: run_original
          run: |
            cd ./test-generation-with-pynguin
            ls -l
            chmod +x ./run_original.sh
            ./run_original.sh "${{ inputs.project-link }}"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

        - name: Run Testgen Tests
          if: ${{ steps.run_original.outcome == 'success' }}
          run: |
            cd ./test-generation-with-pynguin
            ls -l
            chmod +x ./run_testgen.sh
            ./run_testgen.sh "${{ inputs.project-link }}"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

        - name: Run Combined Tests
          if: ${{ steps.run_original.outcome == 'success' }}
          run: |
            cd ./test-generation-with-pynguin
            ls -l
            chmod +x ./run_combined.sh
            ./run_combined.sh "${{ inputs.project-link }}"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

        - name: Zip all the result files
          if: ${{ steps.run_original.outcome == 'success' }}
          run: |
            cd ./test-generation-with-pynguin
            zip -j ../$ZIP_FILE ./*.zip  # -j to junk paths and include only .zip files
            ls -l ../
          shell: bash

        - name: Upload report to GitHub Release
          if: ${{ steps.run_original.outcome == 'success' }}
          uses: Wandalen/wretry.action@master
          with:
            attempt_delay: 60000 # 1 min
            attempt_limit: 10
            action: softprops/action-gh-release@v1
            with: |
              files: ./${{env.ZIP_FILE}}
              tag_name: ${{ inputs.release-name }}
              name: ${{ inputs.release-name }}
              draft: false
              prerelease: true
              token: ${{ secrets.GITHUB_TOKEN }}

